# Spectral OpenAPI Linting Configuration
# Enforces API design patterns and consistency across all specs

extends: ["spectral:oas"]

rules:
  # =============================================================================
  # Standard OpenAPI Rules (from spectral:oas)
  # =============================================================================

  # Disable some overly strict defaults
  info-contact: off
  info-license: off
  oas3-api-servers: warn

  # Disable rules that don't apply to our project structure:
  # - Our example files are raw YAML data, not OpenAPI example objects
  # - Example validation is handled by validate:syntax using AJV
  oas3-examples-value-or-externalValue: off
  oas3-valid-media-example: off

  # =============================================================================
  # HTTP Method Response Codes
  # =============================================================================

  # POST must return 201 Created
  post-must-return-201:
    description: POST operations must return 201 Created
    severity: error
    given: "$.paths[*].post.responses"
    then:
      field: "201"
      function: truthy

  # DELETE must return 204 No Content
  delete-must-return-204:
    description: DELETE operations must return 204 No Content
    severity: error
    given: "$.paths[*].delete.responses"
    then:
      field: "204"
      function: truthy

  # GET single resource must handle 404
  get-single-must-handle-404:
    description: GET operations for single resources must handle 404 Not Found
    severity: error
    given: "$.paths[?(@property.match(/\\{[^}]+\\}$/))].get.responses"
    then:
      field: "404"
      function: truthy

  # =============================================================================
  # Path Naming Conventions
  # =============================================================================

  # Paths should use kebab-case (no underscores or camelCase in path segments)
  # Path parameters like {personId} are allowed (camelCase inside braces is OK)
  path-must-use-kebab-case:
    description: Path segments must use kebab-case (hyphens, not underscores or camelCase)
    severity: error
    given: "$.paths[*]~"
    then:
      function: pattern
      functionOptions:
        # Allows: /persons, /user-profiles, /persons/{personId}, /orders/{orderId}/items
        # Disallows: /userProfiles, /user_profiles
        match: "^(/([a-z][a-z0-9]*(-[a-z0-9]+)*|\\{[a-zA-Z][a-zA-Z0-9]*\\}))+$"

  # =============================================================================
  # Operation ID Conventions
  # =============================================================================

  # Operation IDs should use camelCase
  operation-id-camel-case:
    description: Operation IDs must use camelCase
    severity: error
    given: "$.paths[*][get,post,put,patch,delete].operationId"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z][a-zA-Z0-9]*$"

  # =============================================================================
  # Schema Naming Conventions
  # =============================================================================

  # Schema names should use PascalCase
  schema-names-pascal-case:
    description: Schema names must use PascalCase
    severity: error
    given: "$.components.schemas[*]~"
    then:
      function: pattern
      functionOptions:
        match: "^[A-Z][a-zA-Z0-9]*$"

  # =============================================================================
  # Error Response Consistency
  # =============================================================================
  # Note: We enforce shared error responses via validate:patterns script
  # Spectral rules for this cause false positives on referenced component files

  # =============================================================================
  # Request/Response Content Type
  # =============================================================================

  # All request bodies should use application/json
  request-body-json-only:
    description: Request bodies must use application/json
    severity: error
    given: "$.paths[*][*].requestBody.content"
    then:
      field: "application/json"
      function: truthy

  # All responses should use application/json (except 204)
  response-body-json-only:
    description: Response bodies must use application/json
    severity: error
    given: "$.paths[*][*].responses[?(@property != '204')].content"
    then:
      field: "application/json"
      function: truthy
